In [ ]:
import pandas as pd
import numpy as np
import requests
import json

In [ ]:
!ls data
groc_fn = "data/grocery-stores-QueryResult.csv"

grocery-stores-QueryResult.csv

In [ ]:
def info(df):
    print("Full shape: ", df.shape)
    print(df.columns)
    display(df)

In [ ]:
groc_df = pd.read_csv(groc_fn)
info(groc_df)

Full shape:  (8044, 64)
Index(['censustract', 'state', 'county', 'lilatracts_1and10',
       'lilatracts_halfand10', 'lilatracts_1and20', 'lilatracts_vehicle',
       'urban', 'rural', 'la1and10', 'lahalfand10', 'la1and20',
       'latracts_half', 'latracts1', 'latracts10', 'latracts20', 'hunvflag',
       'groupquartersflag', 'ohu2010', 'numgqtrs', 'pctgqtrs',
       'lowincometracts', 'pop2010', 'uatyp10', 'lapophalf', 'lapophalfshare',
       'lalowihalf', 'lalowihalfshare', 'lakidshalf', 'lakidshalfshare',
       'laseniorshalf', 'laseniorshalfshare', 'lahunvhalf', 'lahunvhalfshare',
       'lapop1', 'lapop1share', 'lalowi1', 'lalowi1share', 'lakids1',
       'lakids1share', 'laseniors1', 'laseniors1share', 'lahunv1',
       'lahunv1share', 'lapop10', 'lapop10share', 'lalowi10', 'lalowi10share',
       'lakids10', 'lakids10share', 'laseniors10', 'laseniors10share',
       'lahunv10', 'lahunv10share', 'lapop20', 'lapop20share', 'lalowi20',
       'lalowi20share', 'lakids20', 'lakids20share', 'laseniors20',
       'laseniors20share', 'lahunv20', 'lahunv20share'],
      dtype='object')

,censustract,state,county,lilatracts_1and10,lilatracts_halfand10,lilatracts_1and20,lilatracts_vehicle,urban,rural,la1and10,...,lapop20,lapop20share,lalowi20,lalowi20share,lakids20,lakids20share,laseniors20,laseniors20share,lahunv20,lahunv20share
0,6001400100,CA,Alameda,False,False,False,False,True,False,True,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,6001400200,CA,Alameda,False,False,False,False,True,False,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,6001400300,CA,Alameda,False,False,False,False,True,False,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,6001400400,CA,Alameda,False,False,False,False,True,False,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,6001400500,CA,Alameda,False,True,False,False,True,False,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8039,6115040800,CA,Yuba,False,False,False,False,False,True,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8040,6115040901,CA,Yuba,False,False,False,False,False,True,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8041,6115040902,CA,Yuba,False,False,False,False,False,True,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8042,6115041000,CA,Yuba,False,False,False,False,False,True,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8043,6115041100,CA,Yuba,False,False,False,False,False,True,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Open Charge Map API Usage

See https://openchargemap.org/site/develop/api

In [ ]:
## Define api parameters
maxresults = "10"
key = "10f52d91-4f2c-44d4-aacc-16dff6c88d99"
long = "-122.431297" ## This is san francisco
lat = "37.773972"
distance = "20"
dist_units = "Miles"
example = "https://api.openchargemap.io/v3/poi/?output=json&countrycode=US&maxresults={maxresults}&compact=true&verbose=false&key={key}&longitude={long}&latitude={lat}&distance={distance}&distanceunit={dist_units}".format(key=key, maxresults=maxresults, long=long, lat=lat, distance=distance, dist_units=dist_units)

response = requests.get(example)
json_response = response.json()

The `AddressInfo` and `Connections` columns have embedded json. This needs to be flattened.

In [ ]:
json_unprocessed_df = pd.DataFrame(json_response)

info(json_unprocessed_df)

Full shape:  (10, 18)
Index(['IsRecentlyVerified', 'ID', 'UUID', 'DataProviderID', 'OperatorID',
       'UsageTypeID', 'UsageCost', 'AddressInfo', 'Connections',
       'NumberOfPoints', 'GeneralComments', 'StatusTypeID',
       'DateLastStatusUpdate', 'DataQualityLevel', 'DateCreated',
       'SubmissionStatusTypeID', 'DataProvidersReference',
       'OperatorsReference'],
      dtype='object')

,IsRecentlyVerified,ID,UUID,DataProviderID,OperatorID,UsageTypeID,UsageCost,AddressInfo,Connections,NumberOfPoints,GeneralComments,StatusTypeID,DateLastStatusUpdate,DataQualityLevel,DateCreated,SubmissionStatusTypeID,DataProvidersReference,OperatorsReference
0,False,71749,F39D4D8F-665B-40EF-AA08-6B2B4AD1EFC2,1,15,1.0,$9.95,"{'ID': 72095, 'Title': 'Whole Foods - Market S...","[{'ID': 102776, 'ConnectionTypeID': 32, 'Statu...",2.0,underground parking.,50.0,2016-11-22T14:22:00Z,1,2016-09-05T17:15:00Z,200,NaN,NaN
1,False,41373,A428ABC3-FF84-4335-8EF0-25BFAB4A2A0C,2,5,1.0,NaN,"{'ID': 41719, 'Title': 'CCSF SFMTA', 'AddressL...","[{'ID': 45215, 'ConnectionTypeID': 9, 'LevelID...",NaN,NaN,NaN,2019-12-24T09:14:00Z,3,2015-02-02T06:34:00Z,100,44979,NaN
2,False,140930,DCF167A5-B380-4A67-9D8A-CAB510AAA17C,2,5,1.0,NaN,"{'ID': 141282, 'Title': 'DGS MAIN', 'AddressLi...","[{'ID': 196706, 'ConnectionTypeID': 1, 'LevelI...",NaN,NaN,50.0,2019-12-24T09:14:00Z,3,2019-12-24T09:14:00Z,100,79330,NaN
3,False,163260,E002B9D1-73E2-453C-BE85-72A82B9E8F2C,1,23,4.0,$0.26/kWh; other tariffs for older cars,"{'ID': 163617, 'Title': 'San Francisco, Ca Sup...","[{'ID': 234818, 'ConnectionTypeID': 27, 'Statu...",12.0,"Charging12 Superchargers, available 24/7, up t...",50.0,2020-08-20T05:54:00Z,1,2020-08-20T05:54:00Z,200,NaN,34648
4,False,41992,9431FE63-98BF-4D8E-9B90-E11302950D89,1,5,1.0,NaN,"{'ID': 42338, 'Title': 'CCSF-SFMTA', 'AddressL...","[{'ID': 50362, 'ConnectionTypeID': 9, 'LevelID...",NaN,NaN,0.0,2016-01-09T11:47:00Z,3,2015-02-23T02:09:00Z,200,NaN,NaN
5,False,159224,6383428F-FBDF-4636-B31E-722ADF7A01FE,2,5,1.0,NaN,"{'ID': 159581, 'Title': 'CCSF-SFMTA', 'Address...","[{'ID': 229352, 'ConnectionTypeID': 1, 'LevelI...",NaN,NaN,50.0,2020-06-26T02:59:00Z,3,2020-06-26T02:59:00Z,100,153503,NaN
6,False,140934,13039214-BEAF-4EBD-B836-B298B8E078D1,2,5,1.0,NaN,"{'ID': 141286, 'Title': 'OPERA PLAZA', 'Addres...","[{'ID': 196713, 'ConnectionTypeID': 1, 'LevelI...",NaN,NaN,50.0,2019-12-24T09:14:00Z,3,2019-12-24T09:14:00Z,100,49995,NaN
7,False,140926,8AEB1737-3C8E-4D29-8912-DEA32D6367C6,2,9,1.0,NaN,"{'ID': 141278, 'Title': 'NEMA Apartments', 'Ad...","[{'ID': 196702, 'ConnectionTypeID': 1, 'LevelI...",NaN,NaN,50.0,2020-06-26T02:59:00Z,3,2019-12-24T09:14:00Z,100,95963,NaN
8,False,8668,B0792C55-9093-4E4C-9AF7-FF33F215A8C0,15,5,2.0,NaN,"{'ID': 8565, 'Title': 'Dr Carlton B Goodlett P...","[{'ID': 6089, 'ConnectionTypeID': 1, 'Referenc...",3.0,NaN,0.0,2017-11-04T14:04:00Z,1,2011-11-11T12:07:00Z,100,1636,NaN
9,False,29746,3A238E4D-2CD1-4B9A-A1C8-F8C5B09B1CBA,15,5,NaN,NaN,"{'ID': 30092, 'Title': '2000 Post St', 'Addres...","[{'ID': 32731, 'ConnectionTypeID': 1, 'Referen...",NaN,NaN,0.0,2017-11-04T14:04:00Z,2,2014-11-29T05:39:00Z,100,35781,NaN

In [ ]:
## Reference: https://towardsdatascience.com/flattening-json-objects-in-python-f5343c794b10
def flatten_json(y):
    out = {}
    
    def flatten(x, name=''):
        if type(x) is dict:
            for a in x:
                flatten(x[a], name + a + '_')
        elif type(x) is list:
            i = 0
            for a in x:
                flatten(a, name + str(i) + '_')
                i += 1
        else:
            out[name[:-1]] = x

    flatten(y)
    return out

In [ ]:
flattend_json_response = [flatten_json(charger) for charger in json_response]
# flattened_dict = flattend_json_response
flattened_json_df = pd.DataFrame(flattend_json_response)

info(flattened_json_df)

Full shape:  (10, 55)
Index(['IsRecentlyVerified', 'ID', 'UUID', 'DataProviderID', 'OperatorID',
       'UsageTypeID', 'UsageCost', 'AddressInfo_ID', 'AddressInfo_Title',
       'AddressInfo_AddressLine1', 'AddressInfo_Town',
       'AddressInfo_StateOrProvince', 'AddressInfo_Postcode',
       'AddressInfo_CountryID', 'AddressInfo_Latitude',
       'AddressInfo_Longitude', 'AddressInfo_Distance',
       'AddressInfo_DistanceUnit', 'Connections_0_ID',
       'Connections_0_ConnectionTypeID', 'Connections_0_StatusTypeID',
       'Connections_0_LevelID', 'Connections_0_Amps', 'Connections_0_Voltage',
       'Connections_0_PowerKW', 'Connections_0_CurrentTypeID',
       'Connections_0_Quantity', 'Connections_1_ID',
       'Connections_1_ConnectionTypeID', 'Connections_1_StatusTypeID',
       'Connections_1_LevelID', 'Connections_1_Amps', 'Connections_1_Voltage',
       'Connections_1_PowerKW', 'Connections_1_CurrentTypeID',
       'Connections_1_Quantity', 'NumberOfPoints', 'GeneralComments',
       'StatusTypeID', 'DateLastStatusUpdate', 'DataQualityLevel',
       'DateCreated', 'SubmissionStatusTypeID', 'DataProvidersReference',
       'AddressInfo_ContactTelephone1', 'AddressInfo_AccessComments',
       'AddressInfo_RelatedURL', 'OperatorsReference', 'Connections_2_ID',
       'Connections_2_ConnectionTypeID', 'Connections_2_StatusTypeID',
       'Connections_2_LevelID', 'Connections_2_CurrentTypeID',
       'Connections_0_Reference', 'Connections_1_Reference'],
      dtype='object')

,IsRecentlyVerified,ID,UUID,DataProviderID,OperatorID,UsageTypeID,UsageCost,AddressInfo_ID,AddressInfo_Title,AddressInfo_AddressLine1,...,AddressInfo_AccessComments,AddressInfo_RelatedURL,OperatorsReference,Connections_2_ID,Connections_2_ConnectionTypeID,Connections_2_StatusTypeID,Connections_2_LevelID,Connections_2_CurrentTypeID,Connections_0_Reference,Connections_1_Reference
0,False,71749,F39D4D8F-665B-40EF-AA08-6B2B4AD1EFC2,1,15,1.0,$9.95,72095,Whole Foods - Market Street,2001 Market Street,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,False,41373,A428ABC3-FF84-4335-8EF0-25BFAB4A2A0C,2,5,1.0,NaN,41719,CCSF SFMTA,360 Grove St,...,24 hours daily,http://www.chargepoint.com/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,False,140930,DCF167A5-B380-4A67-9D8A-CAB510AAA17C,2,5,1.0,NaN,141282,DGS MAIN,505 Van Ness Ave,...,24 hours daily,http://www.chargepoint.com/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,False,163260,E002B9D1-73E2-453C-BE85-72A82B9E8F2C,1,23,4.0,$0.26/kWh; other tariffs for older cars,163617,"San Francisco, Ca Supercharger",601 Van Ness Avenue,...,NaN,NaN,34648,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,False,41992,9431FE63-98BF-4D8E-9B90-E11302950D89,1,5,1.0,NaN,42338,CCSF-SFMTA,1610 Geary Blvd,...,24 hours daily,http://www.mychargepoint.net/,NaN,75098.0,6.0,0.0,2.0,10.0,NaN,NaN
5,False,159224,6383428F-FBDF-4636-B31E-722ADF7A01FE,2,5,1.0,NaN,159581,CCSF-SFMTA,1650 Fillmore St,...,24 hours daily,http://www.chargepoint.com/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,False,140934,13039214-BEAF-4EBD-B836-B298B8E078D1,2,5,1.0,NaN,141286,OPERA PLAZA,601 Van Ness Ave,...,24 hours daily,http://www.chargepoint.com/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,False,140926,8AEB1737-3C8E-4D29-8912-DEA32D6367C6,2,9,1.0,NaN,141278,NEMA Apartments,1411 Market Street,...,MON: 24 hours | TUE: 24 hours | WED: 24 hours ...,http://www.blinkcharging.com/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,False,8668,B0792C55-9093-4E4C-9AF7-FF33F215A8C0,15,5,2.0,NaN,8565,Dr Carlton B Goodlett Pl,Dr Carlton B Goodlett Pl,...,NaN,http://carstations.com/1636,NaN,NaN,NaN,NaN,NaN,NaN,J1772,NEMA5
9,False,29746,3A238E4D-2CD1-4B9A-A1C8-F8C5B09B1CBA,15,5,NaN,NaN,30092,2000 Post St,2000 Post St,...,NaN,http://carstations.com/35781,NaN,NaN,NaN,NaN,NaN,NaN,J1772,NaN